// <auto-generated />
using System;
using Meetup.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Meetup.Data.Migrations
{
    [DbContext(typeof(MeetupContext))]
    [Migration("20180711012658_First_Migration")]
    partial class First_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Meetup.Domain.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Meetup.Domain.MeetupEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("From");

                    b.Property<int?>("GroupId");

                    b.Property<string>("Location");

                    b.Property<DateTime>("To");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Meetups");
                });

            modelBuilder.Entity("Meetup.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Meetup.Domain.UserGroup", b =>
                {
                    b.Property<Guid>("GroupId");

                    b.Property<Guid>("UserId");

                    b.Property<int?>("GroupId1");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("GroupId1");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("Meetup.Domain.UserMeetup", b =>
                {
                    b.Property<Guid>("MeetupId");

                    b.Property<Guid>("UserId");

                    b.Property<int?>("MeetupId1");

                    b.HasKey("MeetupId", "UserId");

                    b.HasIndex("MeetupId1");

                    b.HasIndex("UserId");

                    b.ToTable("UserMeetup");
                });

            modelBuilder.Entity("Meetup.Domain.MeetupEvent", b =>
                {
                    b.HasOne("Meetup.Domain.Group", "Group")
                        .WithMany("Meetups")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("Meetup.Domain.UserGroup", b =>
                {
                    b.HasOne("Meetup.Domain.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId1");

                    b.HasOne("Meetup.Domain.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Meetup.Domain.UserMeetup", b =>
                {
                    b.HasOne("Meetup.Domain.MeetupEvent", "Meetup")
                        .WithMany("Assistants")
                        .HasForeignKey("MeetupId1");

                    b.HasOne("Meetup.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
